// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadDnsCap returns the embedded CollectionSpec for DnsCap.
func LoadDnsCap() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DnsCapBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load DnsCap: %w", err)
	}

	return spec, err
}

// LoadDnsCapObjects loads DnsCap and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*DnsCapObjects
//	*DnsCapPrograms
//	*DnsCapMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadDnsCapObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadDnsCap()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// DnsCapSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsCapSpecs struct {
	DnsCapProgramSpecs
	DnsCapMapSpecs
	DnsCapVariableSpecs
}

// DnsCapProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsCapProgramSpecs struct {
	MagentDnscap *ebpf.ProgramSpec `ebpf:"magent_dnscap"`
}

// DnsCapMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsCapMapSpecs struct {
	MagentDns   *ebpf.MapSpec `ebpf:"magent_dns"`
	MagentStats *ebpf.MapSpec `ebpf:"magent_stats"`
}

// DnsCapVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type DnsCapVariableSpecs struct {
}

// DnsCapObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadDnsCapObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsCapObjects struct {
	DnsCapPrograms
	DnsCapMaps
	DnsCapVariables
}

func (o *DnsCapObjects) Close() error {
	return _DnsCapClose(
		&o.DnsCapPrograms,
		&o.DnsCapMaps,
	)
}

// DnsCapMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadDnsCapObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsCapMaps struct {
	MagentDns   *ebpf.Map `ebpf:"magent_dns"`
	MagentStats *ebpf.Map `ebpf:"magent_stats"`
}

func (m *DnsCapMaps) Close() error {
	return _DnsCapClose(
		m.MagentDns,
		m.MagentStats,
	)
}

// DnsCapVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadDnsCapObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsCapVariables struct {
}

// DnsCapPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadDnsCapObjects or ebpf.CollectionSpec.LoadAndAssign.
type DnsCapPrograms struct {
	MagentDnscap *ebpf.Program `ebpf:"magent_dnscap"`
}

func (p *DnsCapPrograms) Close() error {
	return _DnsCapClose(
		p.MagentDnscap,
	)
}

func _DnsCapClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dnscap_bpfel.o
var _DnsCapBytes []byte
